using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Da単oJudy : MonoBehaviour
{
    public int cantidadDeDa単o = 10;
    private Vida vida;
    private bool cooldown = false;
    private void Start()
    {
        vida = GameObject.FindAnyObjectByType<Vida>();
    }

    private void OnTriggerEnter(Collider other)
    {
        if (other.gameObject.CompareTag("Player")&& !cooldown)
        {
            cooldown = true;
            vida.da単o(cantidadDeDa単o);
            Invoke("delay", 1);
        }
    } 

    public void delay()
    {
        cooldown = false;
    }
}
